### ISSUE TITLE
Feature Request: Examples of patterns

### ISSUE THREAD

**Issue by zwhitchcox** [derhuerst/svg-patterns#2]
I saw where that was a picture of all the different types of patterns on the README.md, but I don't know which picture corresponds to which pattern type. It would be helpful to quickly see all the patterns if possible. Thank you!

**Comment by derhuerst** [comment]
You can see a list of patterns on the [website](https://derhuerst.github.io/svg-patterns/).

**Comment by zwhitchcox** [comment]
Ahhhh ok, thanks!!
